// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Praxis.Modules.Persistencia;

#nullable disable

namespace Praxis.Modules.Persistencia.Migrations
{
    [DbContext(typeof(PraxisDbContext))]
    [Migration("20260905210258_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Praxis.Modules.Assinaturas.Domain.Assinatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacaoId");

                    b.ToTable("assinaturas_assinatura", (string)null);
                });

            modelBuilder.Entity("Praxis.Modules.Assinaturas.Domain.DireitoDeUso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssinaturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FimEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("InicioEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Produto")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssinaturaId", "Produto");

                    b.ToTable("assinaturas_direito_de_uso", (string)null);
                });

            modelBuilder.Entity("Praxis.Modules.Assinaturas.Domain.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssinaturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Confirmado")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ConfirmadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Meio")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssinaturaId");

                    b.ToTable("assinaturas_pagamento", (string)null);
                });

            modelBuilder.Entity("Praxis.Modules.Identidade.Domain.Organizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.ToTable("identidade_organizacao", (string)null);
                });

            modelBuilder.Entity("Praxis.Modules.Identidade.Domain.PerfilDeUso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AreaDeAtuacao")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DorAtual")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RegimePredominante")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Setores")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("identidade_perfil_de_uso", (string)null);
                });

            modelBuilder.Entity("Praxis.Modules.Identidade.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Papel")
                        .HasColumnType("integer");

                    b.Property<string>("RegistroProfissional")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizacaoId");

                    b.ToTable("identidade_usuario", (string)null);
                });

            modelBuilder.Entity("Praxis.Modules.Assinaturas.Domain.DireitoDeUso", b =>
                {
                    b.HasOne("Praxis.Modules.Assinaturas.Domain.Assinatura", null)
                        .WithMany("DireitosDeUso")
                        .HasForeignKey("AssinaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Praxis.Modules.Assinaturas.Domain.Pagamento", b =>
                {
                    b.HasOne("Praxis.Modules.Assinaturas.Domain.Assinatura", null)
                        .WithMany("Pagamentos")
                        .HasForeignKey("AssinaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Praxis.Modules.Identidade.Domain.PerfilDeUso", b =>
                {
                    b.HasOne("Praxis.Modules.Identidade.Domain.Usuario", null)
                        .WithOne("Perfil")
                        .HasForeignKey("Praxis.Modules.Identidade.Domain.PerfilDeUso", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Praxis.Modules.Identidade.Domain.Usuario", b =>
                {
                    b.HasOne("Praxis.Modules.Identidade.Domain.Organizacao", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Praxis.Modules.Assinaturas.Domain.Assinatura", b =>
                {
                    b.Navigation("DireitosDeUso");

                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("Praxis.Modules.Identidade.Domain.Organizacao", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Praxis.Modules.Identidade.Domain.Usuario", b =>
                {
                    b.Navigation("Perfil");
                });
#pragma warning restore 612, 618
        }
    }
}
